import {
  faAddressCard,
  faBell,
  faBookmark,
  faCheckCircle,
  faClock,
  faComment,
  faEnvelope,
  faEnvelopeOpen,
  faFile,
  faFileAlt,
  faFileArchive,
  faFileAudio,
  faFileCode,
  faFileExcel,
  faFileImage,
  faFilePdf,
  faFilePowerpoint,
  faFileVideo,
  faFileWord,
  faFolder,
  faFolderOpen,
  faImage,
  faImages,
  faQuestionCircle,
  faSave,
  faStickyNote,
  faTimesCircle,
  faTrashAlt,
  faUser,
  faUserCircle
} from '@fortawesome/free-regular-svg-icons'
import {
  faBan,
  faChartArea,
  faChartBar,
  faChartLine,
  faCheck,
  faCloudUploadAlt,
  faCog,
  faEdit,
  faExclamation,
  faExclamationCircle,
  faExclamationTriangle,
  faExternalLinkSquareAlt,
  faFileContract,
  faFileCsv,
  faFileDownload,
  faFileExport,
  faFileImport,
  faFileInvoice,
  faFileInvoiceDollar,
  faFileMedical,
  faFileMedicalAlt,
  faFilePrescription,
  faFileSignature,
  faFileUpload,
  faInbox,
  faInfoCircle,
  faLock,
  faLockOpen,
  faPrint,
  faReceipt,
  faReply,
  faShare,
  faSignature,
  faTimes,
  faTrash,
  faUserCheck,
  faUserEdit,
  faUserPlus,
  faUsers,
  faUserTimes
} from '@fortawesome/free-solid-svg-icons'

import { SeamIcon } from '../icon'

// TODO: Decide a good way to do this, so that we don't have to import full icon
// libraries, but still provide icon choices to use from a string. One way could
// be to define a dictionary of app icons that we can use that map a unique
// string to an icon definition.
const knownIcons: { [key: string]: SeamIcon } = {
  faAddressCard,
  faBan,
  faBell,
  faBookmark,
  faChartLine,
  faChartArea,
  faChartBar,
  faCheck,
  faCheckCircle,
  faClock,
  faCloudUploadAlt,
  faComment,
  faCog,
  faEdit,
  faEnvelope,
  faEnvelopeOpen,
  faExclamation,
  faExclamationCircle,
  faExclamationTriangle,
  faExternalLinkSquareAlt,
  faFile,
  faFileAlt,
  faFileArchive,
  faFileAudio,
  faFileCode,
  faFileContract,
  faFileCsv,
  faFileDownload,
  faFileExcel,
  faFileExport,
  faFileImage,
  faFileImport,
  faFileInvoice,
  faFileInvoiceDollar,
  faFileMedical,
  faFileMedicalAlt,
  faFilePdf,
  faFilePowerpoint,
  faFilePrescription,
  faFileSignature,
  faFileUpload,
  faFileVideo,
  faFileWord,
  faFolder,
  faFolderOpen,
  faImage,
  faImages,
  faInbox,
  faInfoCircle,
  faLock,
  faLockOpen,
  faPrint,
  faQuestionCircle,
  faReceipt,
  faReply,
  faSave,
  faShare,
  faSignature,
  faStickyNote,
  faTimes,
  faTimesCircle,
  faTrash,
  faTrashAlt,
  faUser,
  faUserCheck,
  faUserCircle,
  faUserEdit,
  faUserTimes,
  faUsers,
  faUserPlus
}

export function getKnownIcon(iconStr: string): SeamIcon | undefined {
  return knownIcons[iconStr]
}
