import { FormControl } from '@angular/forms'

import { decimalValidator } from './decimal.validator'

describe('decimalValidator', () => {
  it('should return null for empty control', () => {
    expect(decimalValidator(new FormControl())).toBeNull()
    expect(decimalValidator(new FormControl(null))).toBeNull()
    expect(decimalValidator(new FormControl(undefined))).toBeNull()
    expect(decimalValidator(new FormControl([]))).toBeNull()
    expect(decimalValidator(new FormControl(''))).toBeNull()
  })

  it('should succeed for valid decimal control values', () => {
    expect(decimalValidator(new FormControl(0))).toBeNull()
    expect(decimalValidator(new FormControl(1))).toBeNull()
    expect(decimalValidator(new FormControl(-1))).toBeNull()
    expect(decimalValidator(new FormControl(.1))).toBeNull()
    expect(decimalValidator(new FormControl(1.))).toBeNull()
    expect(decimalValidator(new FormControl(0.1))).toBeNull()
    expect(decimalValidator(new FormControl(1.0))).toBeNull()
    expect(decimalValidator(new FormControl(1.1))).toBeNull()
    expect(decimalValidator(new FormControl(-.1))).toBeNull()
    expect(decimalValidator(new FormControl(-1.))).toBeNull()
    expect(decimalValidator(new FormControl(-0.1))).toBeNull()
    expect(decimalValidator(new FormControl(-1.0))).toBeNull()
    expect(decimalValidator(new FormControl(-1.1))).toBeNull()
    expect(decimalValidator(new FormControl(1234567.012345))).toBeNull()
    expect(decimalValidator(new FormControl(-1234567.012345))).toBeNull()
    expect(decimalValidator(new FormControl('0'))).toBeNull()
    expect(decimalValidator(new FormControl('1'))).toBeNull()
    expect(decimalValidator(new FormControl('-1'))).toBeNull()
    expect(decimalValidator(new FormControl('.1'))).toBeNull()
    expect(decimalValidator(new FormControl('1.'))).toBeNull()
    expect(decimalValidator(new FormControl('0.1'))).toBeNull()
    expect(decimalValidator(new FormControl('1.0'))).toBeNull()
    expect(decimalValidator(new FormControl('1.1'))).toBeNull()
    expect(decimalValidator(new FormControl('-.1'))).toBeNull()
    expect(decimalValidator(new FormControl('-1.'))).toBeNull()
    expect(decimalValidator(new FormControl('-0.1'))).toBeNull()
    expect(decimalValidator(new FormControl('-1.0'))).toBeNull()
    expect(decimalValidator(new FormControl('-1.1'))).toBeNull()
    expect(decimalValidator(new FormControl('-1234567.012345'))).toBeNull()
    expect(decimalValidator(new FormControl('-1234567.012345'))).toBeNull()
  })

  it('should fail for non-valid decimal control values', () => {
    expect(decimalValidator(new FormControl('a'))).toEqual({ 'decimal': { 'reason': 'Must be valid decimal number.' } })
    expect(decimalValidator(new FormControl('a-'))).toEqual({ 'decimal': { 'reason': 'Must be valid decimal number.' } })
    expect(decimalValidator(new FormControl('a1'))).toEqual({ 'decimal': { 'reason': 'Must be valid decimal number.' } })
    expect(decimalValidator(new FormControl('a1-'))).toEqual({ 'decimal': { 'reason': 'Must be valid decimal number.' } })
    expect(decimalValidator(new FormControl('1a'))).toEqual({ 'decimal': { 'reason': 'Must be valid decimal number.' } })
    expect(decimalValidator(new FormControl('1a-'))).toEqual({ 'decimal': { 'reason': 'Must be valid decimal number.' } })
    expect(decimalValidator(new FormControl('a.1'))).toEqual({ 'decimal': { 'reason': 'Must be valid decimal number.' } })
    expect(decimalValidator(new FormControl('a.1-'))).toEqual({ 'decimal': { 'reason': 'Must be valid decimal number.' } })
    expect(decimalValidator(new FormControl('1.a'))).toEqual({ 'decimal': { 'reason': 'Must be valid decimal number.' } })
    expect(decimalValidator(new FormControl('1.a-'))).toEqual({ 'decimal': { 'reason': 'Must be valid decimal number.' } })
    expect(decimalValidator(new FormControl('--a'))).toEqual({ 'decimal': { 'reason': 'Must be valid decimal number.' } })
    expect(decimalValidator(new FormControl('a--'))).toEqual({ 'decimal': { 'reason': 'Must be valid decimal number.' } })
    expect(decimalValidator(new FormControl('-a1'))).toEqual({ 'decimal': { 'reason': 'Must be valid decimal number.' } })
    expect(decimalValidator(new FormControl('-1a'))).toEqual({ 'decimal': { 'reason': 'Must be valid decimal number.' } })
    expect(decimalValidator(new FormControl('-a.1'))).toEqual({ 'decimal': { 'reason': 'Must be valid decimal number.' } })
    expect(decimalValidator(new FormControl('-1.a'))).toEqual({ 'decimal': { 'reason': 'Must be valid decimal number.' } })
    expect(decimalValidator(new FormControl('-'))).toEqual({ 'decimal': { 'reason': 'Must be valid decimal number.' } })
    expect(decimalValidator(new FormControl('+'))).toEqual({ 'decimal': { 'reason': 'Must be valid decimal number.' } })
    expect(decimalValidator(new FormControl('--1'))).toEqual({ 'decimal': { 'reason': 'Must be valid decimal number.' } })
    expect(decimalValidator(new FormControl('-+1'))).toEqual({ 'decimal': { 'reason': 'Must be valid decimal number.' } })
    expect(decimalValidator(new FormControl('+-1'))).toEqual({ 'decimal': { 'reason': 'Must be valid decimal number.' } })
    expect(decimalValidator(new FormControl('++1'))).toEqual({ 'decimal': { 'reason': 'Must be valid decimal number.' } })
    expect(decimalValidator(new FormControl('1--'))).toEqual({ 'decimal': { 'reason': 'Must be valid decimal number.' } })
    expect(decimalValidator(new FormControl('1-+'))).toEqual({ 'decimal': { 'reason': 'Must be valid decimal number.' } })
    expect(decimalValidator(new FormControl('1+-'))).toEqual({ 'decimal': { 'reason': 'Must be valid decimal number.' } })
    expect(decimalValidator(new FormControl('1++'))).toEqual({ 'decimal': { 'reason': 'Must be valid decimal number.' } })
    expect(decimalValidator(new FormControl('1..1'))).toEqual({ 'decimal': { 'reason': 'Must be valid decimal number.' } })
    expect(decimalValidator(new FormControl('-1..1'))).toEqual({ 'decimal': { 'reason': 'Must be valid decimal number.' } })
    expect(decimalValidator(new FormControl('..1'))).toEqual({ 'decimal': { 'reason': 'Must be valid decimal number.' } })
    expect(decimalValidator(new FormControl('1..'))).toEqual({ 'decimal': { 'reason': 'Must be valid decimal number.' } })
    expect(decimalValidator(new FormControl('.'))).toEqual({ 'decimal': { 'reason': 'Must be valid decimal number.' } })
    expect(decimalValidator(new FormControl('..'))).toEqual({ 'decimal': { 'reason': 'Must be valid decimal number.' } })
    expect(decimalValidator(new FormControl({}))).toEqual({ 'decimal': { 'reason': 'Must be valid decimal number.' } })
    expect(decimalValidator(new FormControl(NaN))).toEqual({ 'decimal': { 'reason': 'Must be valid decimal number.' } })
    expect(decimalValidator(new FormControl(Infinity))).toEqual({ 'decimal': { 'reason': 'Must be valid decimal number.' } })
    expect(decimalValidator(new FormControl(new Date()))).toEqual({ 'decimal': { 'reason': 'Must be valid decimal number.' } })
    expect(decimalValidator(new FormControl(new Object()))).toEqual({ 'decimal': { 'reason': 'Must be valid decimal number.' } })
    expect(decimalValidator(new FormControl(true))).toEqual({ 'decimal': { 'reason': 'Must be valid decimal number.' } })
    expect(decimalValidator(new FormControl(false))).toEqual({ 'decimal': { 'reason': 'Must be valid decimal number.' } })
    expect(decimalValidator(new FormControl([1]))).toEqual({ 'decimal': { 'reason': 'Must be valid decimal number.' } })
    expect(decimalValidator(new FormControl(['1']))).toEqual({ 'decimal': { 'reason': 'Must be valid decimal number.' } })
  })
})
