import {
  faAddressCard,
  faBell,
  faBookmark,
  faCheckCircle,
  faClock,
  faComment,
  faEnvelope,
  faEnvelopeOpen,
  faFile,
  faFileAlt,
  faFileArchive,
  faFileAudio,
  faFileCode,
  faFileExcel,
  faFileImage,
  faFilePdf,
  faFilePowerpoint,
  faFileVideo,
  faFileWord,
  faFolder,
  faFolderOpen,
  faImage,
  faImages,
  faQuestionCircle,
  faSave,
  faStickyNote,
  faTimesCircle,
  faTrashAlt,
  faUser,
  faUserCircle
} from '@fortawesome/free-regular-svg-icons'
import {
  faBan,
  faChartArea,
  faChartBar,
  faChartLine,
  faCheck,
  faCloudUploadAlt,
  faCog,
  faEdit,
  faExclamation,
  faExclamationCircle,
  faExclamationTriangle,
  faExternalLinkSquareAlt,
  faFileContract,
  faFileCsv,
  faFileDownload,
  faFileExport,
  faFileImport,
  faFileInvoice,
  faFileInvoiceDollar,
  faFileMedical,
  faFileMedicalAlt,
  faFilePrescription,
  faFileSignature,
  faFileUpload,
  faInbox,
  faInfoCircle,
  faLock,
  faLockOpen,
  faPrint,
  faReceipt,
  faReply,
  faShare,
  faSignature,
  faTimes,
  faTrash,
  faUserCheck,
  faUserEdit,
  faUserPlus,
  faUsers,
  faUserTimes
} from '@fortawesome/free-solid-svg-icons'
import { LibIcon } from '@theseam/ui-common/lib/icon'

// TODO: Decide a good way to do this, so that we don't have to import full icon
// libraries, but still provide icon choices to use from a string. One way could
// be to define a dictionary of app icons that we can use that map a unique
// string to an icon definition.
const knownIcons = {
  'faAddressCard': faAddressCard,
  'faBan': faBan,
  'faBell': faBell,
  'faBookmark': faBookmark,
  'faChartLine': faChartLine,
  'faChartArea': faChartArea,
  'faChartBar': faChartBar,
  'faCheck': faCheck,
  'faCheckCircle': faCheckCircle,
  'faClock': faClock,
  'faCloudUploadAlt': faCloudUploadAlt,
  'faComment': faComment,
  'faCog': faCog,
  'faEdit': faEdit,
  'faEnvelope': faEnvelope,
  'faEnvelopeOpen': faEnvelopeOpen,
  'faExclamation': faExclamation,
  'faExclamationCircle': faExclamationCircle,
  'faExclamationTriangle': faExclamationTriangle,
  'faExternalLinkSquareAlt': faExternalLinkSquareAlt,
  'faFile': faFile,
  'faFileAlt': faFileAlt,
  'faFileArchive': faFileArchive,
  'faFileAudio': faFileAudio,
  'faFileCode': faFileCode,
  'faFileContract': faFileContract,
  'faFileCsv': faFileCsv,
  'faFileDownload': faFileDownload,
  'faFileExcel': faFileExcel,
  'faFileExport': faFileExport,
  'faFileImage': faFileImage,
  'faFileImport': faFileImport,
  'faFileInvoice': faFileInvoice,
  'faFileInvoiceDollar': faFileInvoiceDollar,
  'faFileMedical': faFileMedical,
  'faFileMedicalAlt': faFileMedicalAlt,
  'faFilePdf': faFilePdf,
  'faFilePowerpoint': faFilePowerpoint,
  'faFilePrescription': faFilePrescription,
  'faFileSignature': faFileSignature,
  'faFileUpload': faFileUpload,
  'faFileVideo': faFileVideo,
  'faFileWord': faFileWord,
  'faFolder': faFolder,
  'faFolderOpen': faFolderOpen,
  'faImage': faImage,
  'faImages': faImages,
  'faInbox': faInbox,
  'faInfoCircle': faInfoCircle,
  'faLock': faLock,
  'faLockOpen': faLockOpen,
  'faPrint': faPrint,
  'faQuestionCircle': faQuestionCircle,
  'faReceipt': faReceipt,
  'faReply': faReply,
  'faSave': faSave,
  'faShare': faShare,
  'faSignature': faSignature,
  'faStickyNote': faStickyNote,
  'faTimes': faTimes,
  'faTimesCircle': faTimesCircle,
  'faTrash': faTrash,
  'faTrashAlt': faTrashAlt,
  'faUser': faUser,
  'faUserCheck': faUserCheck,
  'faUserCircle': faUserCircle,
  'faUserEdit': faUserEdit,
  'faUserTimes': faUserTimes,
  'faUsers': faUsers,
  'faUserPlus': faUserPlus
}

export function getKnownIcon(iconStr: string): LibIcon | undefined {
  return knownIcons[iconStr]
}
